### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by jdfekete** [ContinuumIO/abstract_rendering#8]
Hi,

I am trying to run the examples distributed with abstract_rendering and none of them work.
blazeDemo.py and demo.py trigger a:
ImportError: No module named blazeglyphs
numpyDemo.py triggers a:
KeyError: 'No object named test in the file'
since the tweets-subset is almost empty.
When I replace it with the CensusTracts.hdf5 dataset commented out (copied from bokeh distribution), I have:
File "/usr/local/lib/python2.7/dist-packages/abstract_rendering/core.py", line 25, in render
    aggregates = aggregator.aggregate(projected, info, screen)
  File "/usr/local/lib/python2.7/dist-packages/abstract_rendering/numpyglyphs.py", line 94, in aggregate
    data = np.hstack([np.fliplr(points[:, 0:2]), coded[:, np.newaxis]])
IndexError: 0-d arrays can only use a single () or a list of newaxes (and a single ...) as an index

**Comment by jbednar** [comment]
I'm having the same issues...

**Comment by jbednar** [comment]
Sample output:

abstract_rendering> ls -l examples/
total 40
-rw-rw-r--  1 jbednar  staff  3493 Jul 27 13:04 blazeDemo.py
-rw-rw-r--  1 jbednar  staff  3912 Jul 27 13:04 demo.py
-rw-rw-r--  1 jbednar  staff  3767 Jul 27 13:04 numpyDemo.py
-rw-rw-r--  1 jbednar  staff   535 Jul 27 13:04 timer.py
-rw-rw-r--  1 jbednar  staff  1307 Jul 27 13:34 timer.pyc
abstract_rendering> python examples/blazeDemo.py 
Traceback (most recent call last):
  File "examples/blazeDemo.py", line 18, in <module>
    import abstract_rendering.blazeglyphs as blzg
ImportError: No module named blazeglyphs
abstract_rendering> python examples/demo.py 
Traceback (most recent call last):
  File "examples/demo.py", line 19, in <module>
    import abstract_rendering.blazeglyphs as blzg
ImportError: No module named blazeglyphs
abstract_rendering> python examples/numpyDemo.py 
Traceback (most recent call last):
...
IOError: File ../data/tweets-subset.hdf does not exist
abstract_rendering> python examples/timer.py
abstract_rendering>

**Comment by bryevdv** [comment]
They have been removed as there is currently no active maintainer for them. New AR work is going to be founded on an extensible Bokeh model system, so that it can be developed at its own rate and maintained independently.

**Comment by bryevdv** [comment]
Well, I just realized this is not the repo I thought it was...
